base:
  use_cuda: True

data:
  data_folder: data
  images_folder: train
  train_dataset: train.json
  val_dataset: dev.json
  test_dataset: test.json
  num_worker: 2

tokenizer:
  padding: max_length
  max_length: 20
  truncation: True
  return_token_type_ids: True
  return_attention_mask: True

text_embedding:
  text_encoder: vinai/phobert-base
  freeze: False
  d_features: 768
  d_model: 512
  dropout: 0.1

vision_embedding:
  image_encoder: google/vit-base-patch16-224-in21k
  freeze: False
  d_features: 768
  d_model: 512
  dropout: 0.1

attention:
  layers: 3
  heads: 8
  d_model: 512
  d_key: 64
  d_value: 64
  d_ff: 2048
  d_feature: 2048
  dropout: 0.1
  use_aoa: False

encoder:
  d_model: 512
  layers: 3

model:
  name: phobert-vit  # Custom name for the multimodal model
  type_model: vilbert
  intermediate_dims: 512
  dropout: 0.1

train:
  output_dir: checkpoint
  seed: 12345
  num_train_epochs: 100
  patience: 5
  learning_rate: 2
  weight_decay: 0.0
  warmup_ratio: 0.0
  warmup_steps: 0
  metric_for_best_model: accuracy
  per_device_train_batch_size: 32
  per_device_valid_batch_size: 32
  per_device_eval_batch_size: 32

metrics:
  metrics_folder: metrics
  metrics_file: metrics.json

inference:
  batch_size: 256